export const indianDistricts = [
  // Andhra Pradesh
  "Anantapur, Andhra Pradesh",
  "Chittoor, Andhra Pradesh",
  "East Godavari, Andhra Pradesh",
  "Guntur, Andhra Pradesh",
  "Krishna, Andhra Pradesh",
  "Kurnool, Andhra Pradesh",
  "Nellore, Andhra Pradesh",
  "Prakasam, Andhra Pradesh",
  "Srikakulam, Andhra Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Vizianagaram, Andhra Pradesh",
  "West Godavari, Andhra Pradesh",
  "YSR Kadapa, Andhra Pradesh",

  // Arunachal Pradesh
  "Itanagar, Arunachal Pradesh",
  "Tawang, Arunachal Pradesh",
  "West Kameng, Arunachal Pradesh",
  "East Kameng, Arunachal Pradesh",
  "Papum Pare, Arunachal Pradesh",

  // Assam
  "Guwahati, Assam",
  "Dibrugarh, Assam",
  "Jorhat, Assam",
  "Nagaon, Assam",
  "Silchar, Assam",
  "Tezpur, Assam",
  "Kamrup, Assam",
  "Barpeta, Assam",

  // Bihar
  "Patna, Bihar",
  "Gaya, Bihar",
  "Bhagalpur, Bihar",
  "Muzaffarpur, Bihar",
  "Purnia, Bihar",
  "Darbhanga, Bihar",
  "Bihar Sharif, Bihar",
  "Arrah, Bihar",
  "Begusarai, Bihar",
  "Katihar, Bihar",
  "Munger, Bihar",
  "Chhapra, Bihar",
  "Samastipur, Bihar",

  // Chhattisgarh
  "Raipur, Chhattisgarh",
  "Bilaspur, Chhattisgarh",
  "Durg, Chhattisgarh",
  "Bhilai, Chhattisgarh",
  "Korba, Chhattisgarh",
  "Rajnandgaon, Chhattisgarh",

  // Delhi
  "Central Delhi, Delhi",
  "East Delhi, Delhi",
  "New Delhi, Delhi",
  "North Delhi, Delhi",
  "North East Delhi, Delhi",
  "North West Delhi, Delhi",
  "Shahdara, Delhi",
  "South Delhi, Delhi",
  "South East Delhi, Delhi",
  "South West Delhi, Delhi",
  "West Delhi, Delhi",

  // Goa
  "North Goa, Goa",
  "South Goa, Goa",
  "Panaji, Goa",
  "Margao, Goa",
  "Vasco da Gama, Goa",

  // Gujarat
  "Ahmedabad, Gujarat",
  "Surat, Gujarat",
  "Vadodara, Gujarat",
  "Rajkot, Gujarat",
  "Bhavnagar, Gujarat",
  "Jamnagar, Gujarat",
  "Junagadh, Gujarat",
  "Gandhinagar, Gujarat",
  "Anand, Gujarat",
  "Nadiad, Gujarat",
  "Morbi, Gujarat",
  "Mehsana, Gujarat",
  "Bharuch, Gujarat",
  "Vapi, Gujarat",
  "Navsari, Gujarat",
  "Veraval, Gujarat",
  "Porbandar, Gujarat",
  "Godhra, Gujarat",
  "Bhuj, Gujarat",

  // Haryana
  "Faridabad, Haryana",
  "Gurgaon, Haryana",
  "Panipat, Haryana",
  "Ambala, Haryana",
  "Yamunanagar, Haryana",
  "Rohtak, Haryana",
  "Hisar, Haryana",
  "Karnal, Haryana",
  "Sonipat, Haryana",
  "Panchkula, Haryana",

  // Himachal Pradesh
  "Shimla, Himachal Pradesh",
  "Mandi, Himachal Pradesh",
  "Solan, Himachal Pradesh",
  "Kangra, Himachal Pradesh",
  "Dharamshala, Himachal Pradesh",
  "Bilaspur, Himachal Pradesh",
  "Hamirpur, Himachal Pradesh",
  "Una, Himachal Pradesh",
  "Kullu, Himachal Pradesh",

  // Jharkhand
  "Ranchi, Jharkhand",
  "Jamshedpur, Jharkhand",
  "Dhanbad, Jharkhand",
  "Bokaro Steel City, Jharkhand",
  "Deoghar, Jharkhand",
  "Hazaribagh, Jharkhand",
  "Giridih, Jharkhand",
  "Ramgarh, Jharkhand",

  // Karnataka
  "Bangalore Urban, Karnataka",
  "Bangalore Rural, Karnataka",
  "Mysore, Karnataka",
  "Mangalore, Karnataka",
  "Hubli-Dharwad, Karnataka",
  "Belgaum, Karnataka",
  "Gulbarga, Karnataka",
  "Davangere, Karnataka",
  "Bellary, Karnataka",
  "Bijapur, Karnataka",
  "Shimoga, Karnataka",
  "Tumkur, Karnataka",
  "Raichur, Karnataka",
  "Bidar, Karnataka",
  "Hospet, Karnataka",
  "Hassan, Karnataka",
  "Udupi, Karnataka",

  // Kerala
  "Thiruvananthapuram, Kerala",
  "Kochi, Kerala",
  "Kozhikode, Kerala",
  "Thrissur, Kerala",
  "Kollam, Kerala",
  "Kannur, Kerala",
  "Alappuzha, Kerala",
  "Kottayam, Kerala",
  "Palakkad, Kerala",
  "Malappuram, Kerala",
  "Ernakulam, Kerala",
  "Idukki, Kerala",
  "Pathanamthitta, Kerala",
  "Wayanad, Kerala",

  // Madhya Pradesh
  "Indore, Madhya Pradesh",
  "Bhopal, Madhya Pradesh",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Ujjain, Madhya Pradesh",
  "Sagar, Madhya Pradesh",
  "Dewas, Madhya Pradesh",
  "Satna, Madhya Pradesh",
  "Ratlam, Madhya Pradesh",
  "Rewa, Madhya Pradesh",
  "Murwara, Madhya Pradesh",
  "Singrauli, Madhya Pradesh",
  "Burhanpur, Madhya Pradesh",
  "Khandwa, Madhya Pradesh",
  "Bhind, Madhya Pradesh",
  "Chhindwara, Madhya Pradesh",
  "Guna, Madhya Pradesh",
  "Shivpuri, Madhya Pradesh",
  "Vidisha, Madhya Pradesh",
  "Chhatarpur, Madhya Pradesh",

  // Maharashtra
  "Mumbai City, Maharashtra",
  "Mumbai Suburban, Maharashtra",
  "Pune, Maharashtra",
  "Nagpur, Maharashtra",
  "Thane, Maharashtra",
  "Nashik, Maharashtra",
  "Aurangabad, Maharashtra",
  "Solapur, Maharashtra",
  "Amravati, Maharashtra",
  "Kolhapur, Maharashtra",
  "Nanded, Maharashtra",
  "Sangli, Maharashtra",
  "Jalgaon, Maharashtra",
  "Akola, Maharashtra",
  "Latur, Maharashtra",
  "Dhule, Maharashtra",
  "Ahmednagar, Maharashtra",
  "Chandrapur, Maharashtra",
  "Parbhani, Maharashtra",
  "Jalna, Maharashtra",
  "Ratnagiri, Maharashtra",
  "Satara, Maharashtra",
  "Beed, Maharashtra",

  // Manipur
  "Imphal, Manipur",
  "Bishnupur, Manipur",
  "Thoubal, Manipur",
  "Churachandpur, Manipur",

  // Meghalaya
  "Shillong, Meghalaya",
  "Tura, Meghalaya",
  "Jowai, Meghalaya",

  // Mizoram
  "Aizawl, Mizoram",
  "Lunglei, Mizoram",
  "Champhai, Mizoram",

  // Nagaland
  "Kohima, Nagaland",
  "Dimapur, Nagaland",
  "Mokokchung, Nagaland",

  // Odisha
  "Bhubaneswar, Odisha",
  "Cuttack, Odisha",
  "Rourkela, Odisha",
  "Brahmapur, Odisha",
  "Sambalpur, Odisha",
  "Puri, Odisha",
  "Balasore, Odisha",
  "Baripada, Odisha",
  "Bhadrak, Odisha",
  "Jharsuguda, Odisha",
  "Jeypore, Odisha",
  "Angul, Odisha",
  "Kendrapara, Odisha",

  // Punjab
  "Ludhiana, Punjab",
  "Amritsar, Punjab",
  "Jalandhar, Punjab",
  "Patiala, Punjab",
  "Bathinda, Punjab",
  "Mohali, Punjab",
  "Pathankot, Punjab",
  "Hoshiarpur, Punjab",
  "Batala, Punjab",
  "Moga, Punjab",
  "Abohar, Punjab",
  "Malerkotla, Punjab",
  "Khanna, Punjab",
  "Barnala, Punjab",
  "Phagwara, Punjab",
  "Muktsar, Punjab",
  "Rajpura, Punjab",
  "Firozpur, Punjab",

  // Rajasthan
  "Jaipur, Rajasthan",
  "Jodhpur, Rajasthan",
  "Kota, Rajasthan",
  "Bikaner, Rajasthan",
  "Ajmer, Rajasthan",
  "Udaipur, Rajasthan",
  "Bhilwara, Rajasthan",
  "Alwar, Rajasthan",
  "Bharatpur, Rajasthan",
  "Sikar, Rajasthan",
  "Sri Ganganagar, Rajasthan",
  "Pali, Rajasthan",
  "Tonk, Rajasthan",
  "Kishangarh, Rajasthan",
  "Beawar, Rajasthan",
  "Hanumangarh, Rajasthan",
  "Dhaulpur, Rajasthan",
  "Gangapur City, Rajasthan",
  "Sawai Madhopur, Rajasthan",
  "Churu, Rajasthan",
  "Jhunjhunu, Rajasthan",
  "Banswara, Rajasthan",
  "Chittorgarh, Rajasthan",
  "Baran, Rajasthan",
  "Bundi, Rajasthan",
  "Dungarpur, Rajasthan",

  // Sikkim
  "Gangtok, Sikkim",
  "Namchi, Sikkim",
  "Gyalshing, Sikkim",

  // Tamil Nadu
  "Chennai, Tamil Nadu",
  "Coimbatore, Tamil Nadu",
  "Madurai, Tamil Nadu",
  "Tiruchirappalli, Tamil Nadu",
  "Salem, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Tiruppur, Tamil Nadu",
  "Ranipet, Tamil Nadu",
  "Nagercoil, Tamil Nadu",
  "Thanjavur, Tamil Nadu",
  "Vellore, Tamil Nadu",
  "Kancheepuram, Tamil Nadu",
  "Erode, Tamil Nadu",
  "Tiruvannamalai, Tamil Nadu",
  "Pollachi, Tamil Nadu",
  "Rajapalayam, Tamil Nadu",
  "Sivakasi, Tamil Nadu",
  "Pudukkottai, Tamil Nadu",
  "Karur, Tamil Nadu",

  // Telangana
  "Hyderabad, Telangana",
  "Warangal, Telangana",
  "Nizamabad, Telangana",
  "Karimnagar, Telangana",
  "Ramagundam, Telangana",
  "Khammam, Telangana",
  "Mahbubnagar, Telangana",
  "Nalgonda, Telangana",
  "Adilabad, Telangana",
  "Suryapet, Telangana",
  "Miryalaguda, Telangana",

  // Tripura
  "Agartala, Tripura",
  "Dharmanagar, Tripura",
  "Udaipur, Tripura",

  // Uttar Pradesh
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Ghaziabad, Uttar Pradesh",
  "Agra, Uttar Pradesh",
  "Meerut, Uttar Pradesh",
  "Varanasi, Uttar Pradesh",
  "Prayagraj, Uttar Pradesh",
  "Bareilly, Uttar Pradesh",
  "Aligarh, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Noida, Uttar Pradesh",
  "Firozabad, Uttar Pradesh",
  "Jhansi, Uttar Pradesh",
  "Muzaffarnagar, Uttar Pradesh",
  "Mathura, Uttar Pradesh",
  "Rampur, Uttar Pradesh",
  "Shahjahanpur, Uttar Pradesh",
  "Farrukhabad, Uttar Pradesh",
  "Ayodhya, Uttar Pradesh",
  "Sitapur, Uttar Pradesh",
  "Bijnor, Uttar Pradesh",
  "Unnao, Uttar Pradesh",
  "Budaun, Uttar Pradesh",
  "Hardoi, Uttar Pradesh",
  "Fatehpur, Uttar Pradesh",
  "Raebareli, Uttar Pradesh",
  "Orai, Uttar Pradesh",
  "Lakhimpur Kheri, Uttar Pradesh",
  "Bahraich, Uttar Pradesh",
  "Sultanpur, Uttar Pradesh",
  "Azamgarh, Uttar Pradesh",
  "Mirzapur, Uttar Pradesh",
  "Deoria, Uttar Pradesh",
  "Basti, Uttar Pradesh",
  "Jaunpur, Uttar Pradesh",
  "Pratapgarh, Uttar Pradesh",
  "Banda, Uttar Pradesh",
  "Etawah, Uttar Pradesh",
  "Mainpuri, Uttar Pradesh",
  "Sonbhadra, Uttar Pradesh",

  // Uttarakhand
  "Dehradun, Uttarakhand",
  "Haridwar, Uttarakhand",
  "Roorkee, Uttarakhand",
  "Haldwani, Uttarakhand",
  "Rudrapur, Uttarakhand",
  "Kashipur, Uttarakhand",
  "Rishikesh, Uttarakhand",
  "Nainital, Uttarakhand",
  "Mussoorie, Uttarakhand",

  // West Bengal
  "Kolkata, West Bengal",
  "Howrah, West Bengal",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Siliguri, West Bengal",
  "Bardhaman, West Bengal",
  "Malda, West Bengal",
  "Baharampur, West Bengal",
  "Habra, West Bengal",
  "Kharagpur, West Bengal",
  "Shantipur, West Bengal",
  "Dankuni, West Bengal",
  "Dhulian, West Bengal",
  "Ranaghat, West Bengal",
  "Haldia, West Bengal",
  "Raiganj, West Bengal",
  "Krishnanagar, West Bengal",
  "Nabadwip, West Bengal",
  "Medinipur, West Bengal",
  "Jalpaiguri, West Bengal",
  "Balurghat, West Bengal",
  "Basirhat, West Bengal",
  "Bankura, West Bengal",
  "Darjeeling, West Bengal",
  "Purulia, West Bengal",
  "Cooch Behar, West Bengal",

  // Union Territories
  "Chandigarh, Chandigarh",
  "Port Blair, Andaman and Nicobar Islands",
  "Silvassa, Dadra and Nagar Haveli and Daman and Diu",
  "Daman, Dadra and Nagar Haveli and Daman and Diu",
  "Diu, Dadra and Nagar Haveli and Daman and Diu",
  "Kavaratti, Lakshadweep",
  "Puducherry, Puducherry",
  "Karaikal, Puducherry",
  "Mahe, Puducherry",
  "Yanam, Puducherry",
  "Srinagar, Jammu and Kashmir",
  "Jammu, Jammu and Kashmir",
  "Anantnag, Jammu and Kashmir",
  "Baramulla, Jammu and Kashmir",
  "Sopore, Jammu and Kashmir",
  "Leh, Ladakh",
  "Kargil, Ladakh",
]
